---
- name: verify | cluster -> check redis cluster node size
  assert:
    that: (groups['redis-cluster'] | length()) == 3 or (groups['redis-cluster'] | length()) == 6
    msg: "redis cluster node size must be 3 or 6"
  when: redis_deploy_type == 'cluster'
  run_once: yes

- name: verify | cluster -> check redis cluster deploy size
  assert:
    that: redis_cluster_node_port_size * (groups['redis-cluster'] | length()) >= 6
    msg: "redis cluster deploy size must be more than 6"
  when: redis_deploy_type == 'cluster'
  run_once: yes
