---
docker_mirror: 'https://get.docker.com'
docker_group: docker

docker_remote: False
docker_remote_bind: 0.0.0.0
docker_tls: True
docker_nontls_port: 2375
docker_tls_port: 2376

docker_pki_key_suffix: '-key.pem'
docker_pki_cert_suffix: '.pem'
docker_pki_dir: '~/pki'

docker_install_method: installer

# This would be different in case of supporting package based install method with package from docker.com
docker_package_name: docker

deployment_platform: docker
no_upstart: "{{ true if deployment_platform == 'docker' }}"
serial_value: 1

docker_version: '17.03'
docker_selinux_version: '17.03'

docker_package_info:
  pkgs:

docker_repo_key_info:
  repo_keys:

docker_repo_info:
  repos:

dockerproject_repo_key_info:
  repo_keys:

dockerproject_repo_info:
  repos:

docker_dns_servers_strict: yes

docker_container_storage_setup: false

# Used to override obsoletes=0
yum_conf: /etc/yum.conf
docker_yum_conf: /etc/yum_docker.conf

# CentOS/RedHat docker-ce repo
docker_rh_repo_base_url: 'https://download.docker.com/linux/centos/7/$basearch/stable'
docker_rh_repo_gpgkey: 'https://download.docker.com/linux/centos/gpg'
# Ubuntu docker-ce repo
docker_ubuntu_repo_base_url: "https://download.docker.com/linux/ubuntu"
docker_ubuntu_repo_gpgkey: 'https://download.docker.com/linux/ubuntu/gpg'
# Debian docker-ce repo
docker_debian_repo_base_url: "https://download.docker.com/linux/debian"
docker_debian_repo_gpgkey: 'https://download.docker.com/linux/debian/gpg'
# dockerproject repo
dockerproject_rh_repo_base_url: 'https://yum.dockerproject.org/repo/main/centos/7'
dockerproject_rh_repo_gpgkey: 'https://yum.dockerproject.org/gpg'
dockerproject_apt_repo_base_url: 'https://apt.dockerproject.org/repo'
dockerproject_apt_repo_gpgkey: 'https://apt.dockerproject.org/gpg'
