---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- include: mariadb_install.yml

- include: mariadb_cluster.yml

- include: mariadb_config.yml
  when:
    - inventory_hostname == haproxy_hosts.keys()[0]

- meta: flush_handlers
