---
local_release_dir: "/tmp/releases"
harbor_version: "1.5.0"
harbor_download_url: http://artifacts.opnfv.org/compass4nfv/package/master/harbor-offline-installer-v1.5.0.tgz
db_server: "{{ groups['db-cluster'][0] }}"
db_server_ip: "{{ hostvars[db_server]['ansible_ssh_host'] }}"


