---
mysql_packages:
  - python-mysqldb
  - mysql-server

maridb_packages:
  - apt-transport-https
  - debconf-utils
  - libaio1
  - libc6
  - libdbd-mysql-perl
  - libgcc1
  - libgcrypt20
  - libstdc++6
  - python-software-properties
  - mariadb-client
  - galera-3
  - rsync
  - socat
  - mariadb-galera-server-10.0

pip_packages: []

services: []

mysql_config:
  - dest: /etc/mysql/my.cnf
    src: my.cnf
  - dest: /etc/mysql/conf.d/wsrep.cnf
    src: wsrep.cnf

mysql_config_dir: /etc/mysql/conf.d
mysql_data_dir: /var/lib/mysql
wsrep_provider_file: "/usr/lib/galera/libgalera_smm.so"
