---
mysql_packages:
  - MySQL-python
  - mysql-server

maridb_packages:
  - MySQL-python
  - MariaDB-Galera-server
  - MariaDB-client
  - galera


pip_packages:
  - pymongo

services: []

mysql_config:
  - dest: /etc/my.cnf
    src: my.cnf
  - dest: /etc/my.cnf.d/wsrep.cnf
    src: wsrep.cnf

mysql_config_dir: /etc/my.cnf.d
mysql_data_dir: /var/lib/mysql

wsrep_provider_file: "/usr/lib64/galera/libgalera_smm.so"
