###################################################
# Docker configurations
#
# docker registry
docker_registry: 10.84.34.155:5000
docker_registry_insecure: True
#
# install docker from package rather than installer from get.docker.com which is default method
docker_install_method: package

#how to service: docker or package 
deploy_by_docker: True


